export const ipos = [
  {
    id: "goair",
    name: "GO AIR",
    desc: "Go Air Private Limited",
    logo: "/public/goair.jpg",
    issueDate: "4th – 7th Oct 2022",
    issueSize: "₹3,600 - 3,700 Cr.",
    priceRange: "₹50 – 60",
    minInvest: "₹50,000",
    lotSize: "100 Shares/Lot",
    listedPrice: "₹55",
    listingGain: "5%",
    about:
      "Go Air is a low-cost airline focused on domestic and international routes with efficient fleet operations.",
  },
  {
    id: "bajaj-energy",
    name: "BAJAJ ENERGY",
    desc: "Bajaj Energy Private Limited",
    logo: "/public/bajaj.jpg",
    issueDate: "4th – 7th Oct 2022",
    issueSize: "₹3600 Crores",
    priceRange: "₹50 – 60",
    minInvest: "₹50,000",
    lotSize: "100 Shares/Lot",
    listedPrice: "₹58",
    listingGain: "8%",
    about:
      "Bajaj Energy operates thermal power plants and focuses on sustainable electricity generation.",
  },
  {
    id: "oyo",
    name: "OYO",
    desc: "OYO Private Limited",
    logo: "/public/oyo.png",
    issueDate: "To be announced",
    issueDt: "12th – 15th Dec 2023",
    issueSize: "₹3,600 – 3,700 Cr",
    priceRange: "₹100 – 200",
    minInvest: "₹50,000",
    lotSize: "150 Shares/Lots",
    listedOn: "15 Dec 22",
    listedPrice: "₹150",
    listingGain: "10%",
    about:
      "OYO is a hospitality tech company providing standardized hotel experiences across multiple countries.",
  },
];
